---
# tasks file for docker-registry
- name: Log into DockerHub
  docker_login:
    username: nadhirghn
    password: 181jmt2261
- name: Tag image
  become: yes
  shell: docker tag nadhirghn/myapp-image nadhirghn/cd_project:latest
  
- name: Push image to DockerHub 
  become: yes
  shell: docker push nadhirghn/cd_project:latest
