- name: Login to Dockerhub
  become: yes
  shell: docker login --username nadhirghn --password dckr_pat_VkER2y2M9lMsyFX9n7BnjgH2cDI
  
- name: Tag image
  become: yes
  shell: docker tag myapp-image nadhirghn/cd_project:latest
  
- name: Push image to DockerHub 
  become: yes
  shell: docker push nadhirghn/cd_project:latest
